title: Gaël Poux-Médard
description: > # this means to ignore newlines until "baseurl:"
  Gaël Poux-Médard, PhD in Applied Mathematics and Computer Science. Personal website: news, bio, publication, teaching, side projects.
permalink: ':title/'
#baseurl: "/GaelPouxMedard/" # the subpath of your site, e.g. /blog
url: "https://github.XXX.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Gaël Poux-Médard # add your name
author-img: photo.png # add your photo
about-author: Post-doctoral scientist in applied mathematics at WHO/IARC. # add description
social-twitter: GaelPoux # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: GaelPouxMedard # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: gaelpouxmedardacademics@gmail.com # add your Email address
social-researchgate: Gael-Poux-Medard
social-scholar: l7yiSqQAAAAJ

# Disqus
discus-identifier: GaelPoux # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
future: false

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
